{% set name = "bluesky-widgets" %}
{% set version = "0.0.16" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/bluesky-widgets-{{ version }}.tar.gz
  sha256: 9c1b97f8328901865aecd8fd9e06f3d960b95de814a62f8c1b3ba3919941e096

build:
  number: 1
  noarch: python
  entry_points:
    - queue-monitor = bluesky_widgets.apps.queue_monitor.main:main
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python {{ python_min }}
  run:
    - bluesky-live >=0.0.7
    - numpy
    - python >={{ python_min }}
    - suitcase-utils <=0.5.3

test:
  imports:
    - bluesky_widgets
    - bluesky_widgets.examples
  commands:
    - pip check
    - which queue-monitor
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/bluesky/bluesky-widgets
  summary: Toolbox of widgets for visualizing streaming data
  license: BSD-3-Clause
  license_file: LICENSE
  doc_url: https://blueskyproject.io/bluesky-widgets
  dev_url: https://github.com/bluesky/bluesky-widgets

extra:
  recipe-maintainers:
    - dmgav
    - mrakitin
    - AbbyGi
    - danielballan
